config/routes.rb
MyProject::Application.routes.draw do
  resources :room_statuses

  resources :users, :collection => {:login => :get}

  get "hub/index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/dropbox.rb
class Dropbox < ActiveRecord::Base
ROOM_STATUS = [["Available", "Available"],["Used", "Used"]]

ROOM_NAME = [["Pool Suite", "Pool Suite"],["Deluxe Suite", "Deluxe Suite"],
             ["Superior Suite", "Superior Suite"],["Deluxe", "Deluxe"],["Superior", "Superior"]]
end

app/models/room_status.rb
class RoomStatus < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def getCurrentUser
    User.find_by_id(session[:user_id])
  end

  def getCurrentUserName
    @name = getCurrentUser.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
def index
     @current_user = User.find_by_id(session[:user_id])
end
end

app/controllers/hub_controller.rb
class HubController < ApplicationController
  def index

  end

end

app/controllers/room_statuses_controller.rb
class RoomStatusesController < ApplicationController
  # GET /room_statuses
  # GET /room_statuses.xml
  def index
    @room_statuses = RoomStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @room_statuses }
    end
  end

  # GET /room_statuses/1
  # GET /room_statuses/1.xml
  def show
    @room_status = RoomStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @room_status }
    end
  end

  # GET /room_statuses/new
  # GET /room_statuses/new.xml
  def new
    @room_status = RoomStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @room_status }
    end
  end

  # GET /room_statuses/1/edit
  def edit
    @room_status = RoomStatus.find(params[:id])
  end

  # POST /room_statuses
  # POST /room_statuses.xml
  def create
    @room_status = RoomStatus.new(params[:room_status])

    respond_to do |format|
      if @room_status.save
        format.html { redirect_to(@room_status, :notice => 'Room status was successfully created.') }
        format.xml  { render :xml => @room_status, :status => :created, :location => @room_status }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @room_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /room_statuses/1
  # PUT /room_statuses/1.xml
  def update
    @room_status = RoomStatus.find(params[:id])

    respond_to do |format|
      if @room_status.update_attributes(params[:room_status])
        format.html { redirect_to(@room_status, :notice => 'Room status was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @room_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /room_statuses/1
  # DELETE /room_statuses/1.xml
  def destroy
    @room_status = RoomStatus.find(params[:id])
    @room_status.destroy

    respond_to do |format|
      format.html { redirect_to(room_statuses_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def show
     if request.post? and params[:user]
       @user = User.new(params[:user])
       user = User.find_by_username_and_pwd(@user.username, @user.pwd)
       if user
         session[:user_id] = user.id
         #flash[:notice] = "Hello! #{user.username}."
         redirect_to :action => :index, :controller => :dashboard
       else
         flash[:notice] = "Invalid name or password."
         @user.pwd = nil
       end
     end
end

def logout
     #flash[:notice] = "Bye " + @cur_user.username
  session[:user_id] = nil
  @cur_user = nil
  redirect_to :action => :index, :controller => :hub
end

def new
  @user = User.new
end

def create
  @user = User.new(params[:user])
  if @user.save
    #flash[:notice] = "Welcome on board" + @user.username
    redirect_to :action => :index, :controller => :hub
  else
    render :action => "new"
  end
end

  def currentUser
    @currentUser = session[:user_id]
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hub_helper.rb
module HubHelper
end

app/helpers/room_statuses_helper.rb
module RoomStatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
Hello  <b class="ize"><%= @current_user.name %></b>

<%= link_to_unless_current "Room Status", :controller => :room_statuses, :action => :index %>

<%= link_to_unless_current "Logout", :controller => "users", :action => "logout" %>

app/views/hub/index.html.erb
<h1>Hub#index</h1>
<p>Find me in app/views/hub/index.html.erb</p>



<%= link_to_unless_current "Register", :controller => "users", :action => "new" %>|
<%= link_to_unless_current "Log in", :controller => "users", :action => "show"%>

<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>
<% yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyProject</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/room_statuses/_form.html.erb
<%= form_for(@room_status) do |f| %>
  <% if @room_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room_status.errors.count, "error") %> prohibited this room_status from being saved:</h2>

      <ul>
      <% @room_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_num %><br />
    <%= f.text_field :room_num %>
  </div>
  <div class="field">
    <%= f.label :room_name %><br />
    <%= f.select :room_name, Dropbox::ROOM_NAME %>
  </div>
  <div class="field">
    <%= f.label :room_status %><br />
    <%= f.select:room_status, Dropbox::ROOM_STATUS %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/room_statuses/edit.html.erb
<h1>Editing room_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @room_status %> |
<%= link_to 'Back', room_statuses_path %>

app/views/room_statuses/index.html.erb
<h1>Room Status</h1>

<table align="center"style="outline-style:double;">
  <tr>
    <th>Room Number</th>
    <th><dd>Room Name</dd></th>
    <th><dd>Room Status</dd></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @room_statuses.each do |room_status| %>
  <tr align="center">
    <td><%= room_status.room_num %></td>
    <td><%= room_status.room_name %></td>
    <td><%= room_status.room_status %></td>
    <td><%= link_to 'Show', room_status %></td>
    <td><%= link_to 'Edit', edit_room_status_path(room_status) %></td>
    <td><%= link_to 'Destroy', room_status, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room status', new_room_status_path %>
<%= link_to_unless_current "Home", :controller => :dashboard, :action => :index %>

app/views/room_statuses/new.html.erb
<h1>New room_status</h1>

<%= render 'form' %>

<%= link_to 'Back', room_statuses_path %>

app/views/room_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Room num:</b>
  <%= @room_status.room_num %>
</p>

<p>
  <b>Room name:</b>
  <%= @room_status.room_name %>
</p>

<p>
  <b>Room status:</b>
  <%= @room_status.room_status %>
</p>


<%= link_to 'Edit', edit_room_status_path(@room_status) %> |
<%= link_to 'Back', room_statuses_path %>

app/views/users/logout.html.erb
<% if session[:user_id] %>
<%= link_to_unless_current "Logout", :controller => "users", :action => "logout" %>
<% else %>
<%= link_to_unless_current "Register", :controller => "users", :action => "new" %>
<%= link_to_unless_current "Login", :controller => "users", :action => "show" %>
<% end %>


<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>
<% yield %>

app/views/users/new.html.erb
<% form_for @user do |f| %>
Username <%= f.text_field :username %><br/>
Password <%= f.password_field :pwd %><br/>
Name <%= f.text_field :name %><br/>
Surname <%= f.text_field :surname %><br/>
Nickname <%= f.text_field :nickname %><br/>
Sex <%= f.text_field :sex %><br/>
Age <%= f.text_field :age %><br/>
Address <%= f.text_field :address %><br/>
Role <%= f.text_field :role %><br/>
Email <%= f.text_field :email %><br/>
Tel <%= f.text_field :tel %>

<%= submit_tag "Register", :url => { :action => "create"}, :method => :post %>

<% end %>

app/views/users/show.html.erb
<% form_for :user do |f| %>
Username <%= f.text_field :username %><br/>
Password <%= f.password_field :pwd %>
<%= submit_tag "Log in", :url => { :action => "show"}, :method => :post %>
<% end %>